POST http://localhost:4000/app/signup
Content-Type: application/json

{
        "FullName":"Khaqan Aamir",
        "Email":"khaqanaamir92@gmail.com",
        "PhoneNumber":"03305859181!",
        "City":"Rawalpindi",
        "Address":"Usman Block, Bahriatown",
        "Password":"khaqan123",
        "Gender":"Male"
}